name: tests

on:
  push:
    branches: [main]
  pull_request:
  merge_group:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: install dependencies
        run: |
          sudo apt update
          sudo apt install -y libfmt-dev
      - name: build library and tests
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          cmake --build .
      - name: run tests
        run: ctest --test-dir build/test --output-on-failure
